version: "3.3"

services:
  db:
    image: mysql:5.7
    container_name: DB_Wordpress
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - "$PWD:/var/www/html"
      - "$PWD/.docker/backup:/tmp/backup"
      - "$PWD/.docker/log:/tmp/log"
    ports:
      - "8000:80"
#    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
    env_file: .env
volumes:
  db_data: {}
